In [1]:
import pandas as pd

In [2]:
coffee = pd.read_csv('./warmup-data\coffee.csv')

In [4]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [5]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [11]:
results = pd.read_parquet('./data/results.parquet')

ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.

^C
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting pyarrow
  Obtaining dependency information for pyarrow from https://files.pythonhosted.org/packages/54/96/46613131b4727f10fd2ffa6d0d6f02efcc09a0e7374eff3b5771548aa95b/pyarrow-20.0.0-cp311-cp311-win_amd64.whl.metadata
  Downloading pyarrow-20.0.0-cp311-cp311-win_amd64.whl.metadata (3.4 kB)
Downloading pyarrow-20.0.0-cp311-cp311-win_amd64.whl (25.8 MB)
   ---------------------------------------- 0.0/25.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/25.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/25.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/25.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/25.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/25.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/25.8 MB 299.4 kB/s eta 0:01:26
   ---------------------------------------- 0.2/25.8 MB 700.2 kB/s eta 0:00:37
    --------------------------------------- 0.3/25.8 MB 1.2 MB/s eta 0:00:22
   - -------------------------------------- 0.8/25.8 MB 2.3 MB/s eta 0:00:11
   - -------------------------------------- 1.3/25.8 MB 3.4 MB/s eta 0:00:08
   -- ------------------------------------- 1.7/25.8 MB 4.1 MB/s eta 0:00:06
   --- ------------------------------------ 2.2/25.8 MB 4.8 MB/s eta 0:00:05
   ---- ----------------------------------- 2.6/25.8 MB 5.1 MB/s eta 0:00:05
   ---- ----------------------------------- 2.9/25.8 MB 5.2 MB/s eta 0:00:05
   ---- ----------------------------------- 3.2/25.8 MB 5.2 MB/s eta 0:00:05
   ------ --------------------------------- 4.0/25.8 MB 6.2 MB/s eta 0:00:04
   ------ --------------------------------- 4.5/25.8 MB 6.3 MB/s eta 0:00:04
   ------- -------------------------------- 5.1/25.8 MB 6.8 MB/s eta 0:00:04
   -------- ------------------------------- 5.6/25.8 MB 7.0 MB/s eta 0:00:03
   --------- ------------------------------ 6.0/25.8 MB 7.1 MB/s eta 0:00:03
   --------- ------------------------------ 6.3/25.8 MB 7.1 MB/s eta 0:00:03
   ---------- ----------------------------- 7.0/25.8 MB 7.4 MB/s eta 0:00:03
   ----------- ---------------------------- 7.2/25.8 MB 7.3 MB/s eta 0:00:03
   ----------- ---------------------------- 7.7/25.8 MB 7.4 MB/s eta 0:00:03
   ------------ --------------------------- 7.9/25.8 MB 7.3 MB/s eta 0:00:03
   ------------ --------------------------- 8.0/25.8 MB 7.3 MB/s eta 0:00:03
   ------------ --------------------------- 8.3/25.8 MB 7.1 MB/s eta 0:00:03
   ------------ --------------------------- 8.3/25.8 MB 6.9 MB/s eta 0:00:03
   ------------- -------------------------- 8.4/25.8 MB 6.6 MB/s eta 0:00:03
   ------------- -------------------------- 8.5/25.8 MB 6.5 MB/s eta 0:00:03
   ------------- -------------------------- 8.7/25.8 MB 6.4 MB/s eta 0:00:03
   ------------- -------------------------- 8.8/25.8 MB 6.3 MB/s eta 0:00:03
   ------------- -------------------------- 9.0/25.8 MB 6.2 MB/s eta 0:00:03
   -------------- ------------------------- 9.1/25.8 MB 6.1 MB/s eta 0:00:03
   -------------- ------------------------- 9.2/25.8 MB 6.0 MB/s eta 0:00:03
   -------------- ------------------------- 9.4/25.8 MB 5.9 MB/s eta 0:00:03
   -------------- ------------------------- 9.5/25.8 MB 5.8 MB/s eta 0:00:03
   --------------- ------------------------ 9.7/25.8 MB 5.7 MB/s eta 0:00:03
   --------------- ------------------------ 9.9/25.8 MB 5.7 MB/s eta 0:00:03
   --------------- ------------------------ 10.0/25.8 MB 5.6 MB/s eta 0:00:03
   --------------- ------------------------ 10.1/25.8 MB 5.5 MB/s eta 0:00:03
   --------------- ------------------------ 10.3/25.8 MB 6.0 MB/s eta 0:00:03
   ---------------- ----------------------- 10.4/25.8 MB 6.1 MB/s eta 0:00:03
   ---------------- ----------------------- 10.4/25.8 MB 5.9 MB/s eta 0:00:03
   ---------------- ----------------------- 10.5/25.8 MB 5.9 MB/s eta 0:00:03
   ---------------- ----------------------- 10.6/25.8 MB 5.7 MB/s eta 0:00:03
   ---------------- ----------------------- 10.7/25.8 MB 5.6 MB/s eta 0:00:03
   ---------------- ----------------------- 10.7/25.8 MB 5.5 MB/s eta 0:00:03
   ---------------- ----------------------- 10.8/25.8 MB 5.4 MB/s eta 0:00:03
   ---------------- ----------------------- 10.9/25.8 MB 5.3 MB/s eta 0:00:03
   ----------------- ---------------------- 11.0/25.8 MB 5.2 MB/s eta 0:00:03
   ----------------- ---------------------- 11.1/25.8 MB 5.2 MB/s eta 0:00:03
   ----------------- ---------------------- 11.2/25.8 MB 5.0 MB/s eta 0:00:03
   ----------------- ---------------------- 11.3/25.8 MB 5.0 MB/s eta 0:00:03
   ----------------- ---------------------- 11.4/25.8 MB 4.9 MB/s eta 0:00:03
   ----------------- ---------------------- 11.5/25.8 MB 4.7 MB/s eta 0:00:04
   ------------------ --------------------- 11.6/25.8 MB 4.7 MB/s eta 0:00:04
   ------------------ --------------------- 11.7/25.8 MB 4.6 MB/s eta 0:00:04
   ------------------ --------------------- 11.8/25.8 MB 4.5 MB/s eta 0:00:04
   ------------------ --------------------- 12.0/25.8 MB 4.5 MB/s eta 0:00:04
   ------------------ --------------------- 12.1/25.8 MB 4.4 MB/s eta 0:00:04
   ------------------ --------------------- 12.2/25.8 MB 4.3 MB/s eta 0:00:04
   ------------------- -------------------- 12.3/25.8 MB 4.3 MB/s eta 0:00:04
   ------------------- -------------------- 12.4/25.8 MB 4.2 MB/s eta 0:00:04
   ------------------- -------------------- 12.6/25.8 MB 4.1 MB/s eta 0:00:04
   ------------------- -------------------- 12.7/25.8 MB 4.1 MB/s eta 0:00:04
   ------------------- -------------------- 12.9/25.8 MB 4.0 MB/s eta 0:00:04
   -------------------- ------------------- 13.0/25.8 MB 4.0 MB/s eta 0:00:04
   -------------------- ------------------- 13.1/25.8 MB 4.0 MB/s eta 0:00:04
   -------------------- ------------------- 13.1/25.8 MB 3.9 MB/s eta 0:00:04
   -------------------- ------------------- 13.3/25.8 MB 3.9 MB/s eta 0:00:04
   -------------------- ------------------- 13.4/25.8 MB 3.9 MB/s eta 0:00:04
   --------------------- ------------------ 13.6/25.8 MB 3.8 MB/s eta 0:00:04
   --------------------- ------------------ 13.7/25.8 MB 3.7 MB/s eta 0:00:04
   --------------------- ------------------ 13.8/25.8 MB 3.7 MB/s eta 0:00:04
   --------------------- ------------------ 14.0/25.8 MB 3.6 MB/s eta 0:00:04
   --------------------- ------------------ 14.0/25.8 MB 3.6 MB/s eta 0:00:04
   ---------------------- ----------------- 14.2/25.8 MB 3.5 MB/s eta 0:00:04
   ---------------------- ----------------- 14.3/25.8 MB 3.5 MB/s eta 0:00:04
   ---------------------- ----------------- 14.4/25.8 MB 3.5 MB/s eta 0:00:04
   ---------------------- ----------------- 14.5/25.8 MB 3.4 MB/s eta 0:00:04
   ---------------------- ----------------- 14.6/25.8 MB 3.4 MB/s eta 0:00:04
   ---------------------- ----------------- 14.7/25.8 MB 3.3 MB/s eta 0:00:04
   ----------------------- ---------------- 14.9/25.8 MB 3.3 MB/s eta 0:00:04
   ----------------------- ---------------- 15.0/25.8 MB 3.3 MB/s eta 0:00:04
   ----------------------- ---------------- 15.1/25.8 MB 3.2 MB/s eta 0:00:04
   ----------------------- ---------------- 15.2/25.8 MB 3.2 MB/s eta 0:00:04
   ----------------------- ---------------- 15.3/25.8 MB 3.1 MB/s eta 0:00:04
   ------------------------ --------------- 15.5/25.8 MB 3.1 MB/s eta 0:00:04
   ------------------------ --------------- 15.6/25.8 MB 3.1 MB/s eta 0:00:04
   ------------------------ --------------- 15.8/25.8 MB 3.0 MB/s eta 0:00:04
   ------------------------ --------------- 15.9/25.8 MB 3.0 MB/s eta 0:00:04
   ------------------------ --------------- 16.0/25.8 MB 3.0 MB/s eta 0:00:04
   ------------------------ --------------- 16.1/25.8 MB 3.0 MB/s eta 0:00:04
   ------------------------- -------------- 16.2/25.8 MB 2.9 MB/s eta 0:00:04
   ------------------------- -------------- 16.2/25.8 MB 2.9 MB/s eta 0:00:04
   ------------------------- -------------- 16.4/25.8 MB 2.9 MB/s eta 0:00:04
   ------------------------- -------------- 16.4/25.8 MB 2.9 MB/s eta 0:00:04
   ------------------------- -------------- 16.6/25.8 MB 2.8 MB/s eta 0:00:04
   ------------------------- -------------- 16.6/25.8 MB 2.8 MB/s eta 0:00:04
   ------------------------- -------------- 16.7/25.8 MB 2.8 MB/s eta 0:00:04
   ------------------------- -------------- 16.7/25.8 MB 2.8 MB/s eta 0:00:04
   -------------------------- ------------- 16.8/25.8 MB 2.7 MB/s eta 0:00:04
   -------------------------- ------------- 16.8/25.8 MB 2.7 MB/s eta 0:00:04
   -------------------------- ------------- 16.8/25.8 MB 2.7 MB/s eta 0:00:04
   -------------------------- ------------- 16.9/25.8 MB 2.6 MB/s eta 0:00:04
   -------------------------- ------------- 16.9/25.8 MB 2.6 MB/s eta 0:00:04
   -------------------------- ------------- 17.0/25.8 MB 2.5 MB/s eta 0:00:04
   -------------------------- ------------- 17.0/25.8 MB 2.5 MB/s eta 0:00:04
   -------------------------- ------------- 17.1/25.8 MB 2.5 MB/s eta 0:00:04
   -------------------------- ------------- 17.2/25.8 MB 2.5 MB/s eta 0:00:04
   -------------------------- ------------- 17.2/25.8 MB 2.4 MB/s eta 0:00:04
   -------------------------- ------------- 17.3/25.8 MB 2.4 MB/s eta 0:00:04
   -------------------------- ------------- 17.4/25.8 MB 2.4 MB/s eta 0:00:04
   --------------------------- ------------ 17.5/25.8 MB 2.4 MB/s eta 0:00:04
   --------------------------- ------------ 17.5/25.8 MB 2.4 MB/s eta 0:00:04
   --------------------------- ------------ 17.6/25.8 MB 2.3 MB/s eta 0:00:04
   --------------------------- ------------ 17.6/25.8 MB 2.3 MB/s eta 0:00:04
   --------------------------- ------------ 17.7/25.8 MB 2.3 MB/s eta 0:00:04
   --------------------------- ------------ 17.7/25.8 MB 2.3 MB/s eta 0:00:04
   --------------------------- ------------ 17.9/25.8 MB 2.3 MB/s eta 0:00:04
   --------------------------- ------------ 18.0/25.8 MB 2.2 MB/s eta 0:00:04
   --------------------------- ------------ 18.0/25.8 MB 2.2 MB/s eta 0:00:04
   ---------------------------- ----------- 18.1/25.8 MB 2.2 MB/s eta 0:00:04
   ---------------------------- ----------- 18.2/25.8 MB 2.2 MB/s eta 0:00:04
   ---------------------------- ----------- 18.3/25.8 MB 2.2 MB/s eta 0:00:04
   ---------------------------- ----------- 18.4/25.8 MB 2.2 MB/s eta 0:00:04
   ---------------------------- ----------- 18.6/25.8 MB 2.2 MB/s eta 0:00:04
   ---------------------------- ----------- 18.7/25.8 MB 2.2 MB/s eta 0:00:04
   ----------------------------- ---------- 18.8/25.8 MB 2.2 MB/s eta 0:00:04
   ----------------------------- ---------- 18.9/25.8 MB 2.2 MB/s eta 0:00:04
   ----------------------------- ---------- 19.0/25.8 MB 2.2 MB/s eta 0:00:04
   ----------------------------- ---------- 19.1/25.8 MB 2.2 MB/s eta 0:00:04
   ----------------------------- ---------- 19.3/25.8 MB 2.2 MB/s eta 0:00:03
   ------------------------------ --------- 19.4/25.8 MB 2.2 MB/s eta 0:00:03
   ------------------------------ --------- 19.5/25.8 MB 2.2 MB/s eta 0:00:03
   ------------------------------ --------- 19.6/25.8 MB 2.2 MB/s eta 0:00:03
   ------------------------------ --------- 19.8/25.8 MB 2.2 MB/s eta 0:00:03
   ------------------------------- -------- 20.0/25.8 MB 2.2 MB/s eta 0:00:03
   ------------------------------- -------- 20.1/25.8 MB 2.2 MB/s eta 0:00:03
   ------------------------------- -------- 20.3/25.8 MB 2.2 MB/s eta 0:00:03
   ------------------------------- -------- 20.5/25.8 MB 2.2 MB/s eta 0:00:03
   -------------------------------- ------- 20.6/25.8 MB 2.2 MB/s eta 0:00:03
   -------------------------------- ------- 20.8/25.8 MB 2.2 MB/s eta 0:00:03
   -------------------------------- ------- 21.0/25.8 MB 2.3 MB/s eta 0:00:03
   -------------------------------- ------- 21.1/25.8 MB 2.3 MB/s eta 0:00:03
   -------------------------------- ------- 21.2/25.8 MB 2.3 MB/s eta 0:00:03
   --------------------------------- ------ 21.4/25.8 MB 2.3 MB/s eta 0:00:02
   --------------------------------- ------ 21.6/25.8 MB 2.3 MB/s eta 0:00:02
   --------------------------------- ------ 21.8/25.8 MB 2.3 MB/s eta 0:00:02
   ---------------------------------- ----- 22.0/25.8 MB 2.4 MB/s eta 0:00:02
   ---------------------------------- ----- 22.2/25.8 MB 2.4 MB/s eta 0:00:02
   ---------------------------------- ----- 22.4/25.8 MB 2.4 MB/s eta 0:00:02
   ----------------------------------- ---- 22.6/25.8 MB 2.4 MB/s eta 0:00:02
   ----------------------------------- ---- 22.8/25.8 MB 2.4 MB/s eta 0:00:02
   ----------------------------------- ---- 23.0/25.8 MB 2.5 MB/s eta 0:00:02
   ------------------------------------ --- 23.2/25.8 MB 2.5 MB/s eta 0:00:02
   ------------------------------------ --- 23.3/25.8 MB 2.5 MB/s eta 0:00:01
   ------------------------------------ --- 23.5/25.8 MB 2.5 MB/s eta 0:00:01
   ------------------------------------ --- 23.7/25.8 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 23.9/25.8 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 24.2/25.8 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 24.4/25.8 MB 2.6 MB/s eta 0:00:01
   -------------------------------------- - 24.7/25.8 MB 2.6 MB/s eta 0:00:01
   -------------------------------------- - 24.9/25.8 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  25.2/25.8 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  25.4/25.8 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  25.6/25.8 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  25.8/25.8 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  25.8/25.8 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 25.8/25.8 MB 2.7 MB/s eta 0:00:00
Installing collected packages: pyarrow
Successfully installed pyarrow-20.0.0

In [13]:
pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\raiha\appdata\local\programs\python\python311\lib\site-packages (20.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
import pandas as pd
results = pd.read_parquet('./data/results.parquet')

In [15]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [18]:
olympics_data = pd.read_excel('./data/olympics-data.xlsx')
bios = pd.read_csv('./data/bios.csv')

In [17]:
olympics_data

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [19]:
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35